# Generated by Django 5.2 on 2026-02-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Активный'),
        ),
    ]
