# Generated by Django 5.2 on 2026-02-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_student_photo_alter_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(blank=True, help_text='только латинские', max_length=255, null=True, verbose_name='URL'),
        ),
    ]
